#!/bin/bash

export MODULEPATH=$MODULEPATH:/projects/community/modulefiles
module load gcc/9.2.0-gc563
module load cuda

rm nvc_main.x

CXX="nvcc"

NVCFLAG="-g -G -O3 -std=c++17 -Xcompiler -std=c++17 -Xcompiler -fopenmp -Xcompiler -fpermissive -x cu -arch=sm_52"
NVLFLAG="-g -G -lgomp -std=c++17 -Xcompiler -std=c++17 -arch=sm_52"

$CXX $NVCFLAG -dc axpy.cu && echo "Finished axpy.cu" &

$CXX $NVCFLAG -dc main.cpp && echo "Finished main.cpp" &

$CXX $NVCFLAG -dc read_data.cpp && echo "Finished read_data.cpp" &

$CXX $NVCFLAG -dc data_struct.cpp && echo "Finished data_struct.cpp" &

$CXX $NVCFLAG -dc VDW_Coulomb.cu && echo "Finished VDW_Coulomb.cu" &

wait

$CXX $NVLFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x ; echo "Finished Linking"

rm *.o
