#!/bin/bash

rm nvc_main.x

CXX="nvcc"

NVCFLAG="-O3 -std=c++20 -Xcompiler -std=c++20 -Xcompiler -fopenmp -Xcompiler -fpermissive -x cu"
NVLFLAG="-Xcompiler -fopenmp -std=c++20 -Xcompiler -std=c++20"

$CXX $NVCFLAG -dc axpy.cu && echo "Finished axpy.cu" &

$CXX $NVCFLAG -dc main.cpp && echo "Finished main.cpp" &

$CXX $NVCFLAG -dc read_data.cpp && echo "Finished read_data.cpp" &

$CXX $NVCFLAG -dc data_struct.cpp && echo "Finished data_struct.cpp" &

$CXX $NVCFLAG -dc VDW_Coulomb.cu && echo "Finished VDW_Coulomb.cu" &

wait

$CXX $NVLFLAG main.o read_data.o axpy.o data_struct.o VDW_Coulomb.o -o nvc_main.x ; echo "Finished Linking"

rm *.o
